# Question

Will the code work? Why or why not?

```js
const getUsers = async () => {
  const url = 'https://jsonplaceholder.typicode.com/users';
  const users = await fetch(url).then(r => r.json()).catch((err) => []);
  console.log(users)
  return users;
}
getUsers()
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
    This code would not work? Because we have a .then() and .catch() inside of the async.


# Teacher Feedback

The code will actually work! How does `.then()` work? What about `.catch()`? Do they conflict with async/await?  

Score: 1/3